version: "3"
 
services:
  job-portal:
    container_name: job-portal
    image: "job-portal"
    ports:
      - "8080:8080"
    build: .
    env_file:
      - .env
      - .app.postgres.env
      - .app.redis.env
      - .app.private.key.env
      - .app.public.key.env
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .postgres.env
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=admin
    #   - POSTGRES_DB=finalAssing
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    # env_file:
    #   - .redis.env
    