// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source service.go -destination service_mock.go -package services
//
// Package services is a generated GoMock package.
package services

import (
	context "context"
	models "finalAssing/internal/models"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockService) Authenticate(ctx context.Context, email, password string) (jwt.RegisteredClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, email, password)
	ret0, _ := ret[0].(jwt.RegisteredClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockServiceMockRecorder) Authenticate(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockService)(nil).Authenticate), ctx, email, password)
}

// CreateCompany mocks base method.
func (m *MockService) CreateCompany(ctx context.Context, newComp models.Company) (models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompany", ctx, newComp)
	ret0, _ := ret[0].(models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompany indicates an expected call of CreateCompany.
func (mr *MockServiceMockRecorder) CreateCompany(ctx, newComp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompany", reflect.TypeOf((*MockService)(nil).CreateCompany), ctx, newComp)
}

// CreateUser mocks base method.
func (m *MockService) CreateUser(ctx context.Context, nu models.NewUser) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, nu)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockServiceMockRecorder) CreateUser(ctx, nu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockService)(nil).CreateUser), ctx, nu)
}

// FIlterApplication mocks base method.
func (m *MockService) FIlterApplication(ctx context.Context, applicantList []*models.ApplicantReq) ([]*models.ApplicantRespo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FIlterApplication", ctx, applicantList)
	ret0, _ := ret[0].([]*models.ApplicantRespo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FIlterApplication indicates an expected call of FIlterApplication.
func (mr *MockServiceMockRecorder) FIlterApplication(ctx, applicantList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FIlterApplication", reflect.TypeOf((*MockService)(nil).FIlterApplication), ctx, applicantList)
}

// FetchCompanyByID mocks base method.
func (m *MockService) FetchCompanyByID(ctx context.Context, companyId string) (models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCompanyByID", ctx, companyId)
	ret0, _ := ret[0].(models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCompanyByID indicates an expected call of FetchCompanyByID.
func (mr *MockServiceMockRecorder) FetchCompanyByID(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCompanyByID", reflect.TypeOf((*MockService)(nil).FetchCompanyByID), ctx, companyId)
}

// FetchJobByCompanyId mocks base method.
func (m *MockService) FetchJobByCompanyId(ctx context.Context, companyId string) ([]models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJobByCompanyId", ctx, companyId)
	ret0, _ := ret[0].([]models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobByCompanyId indicates an expected call of FetchJobByCompanyId.
func (mr *MockServiceMockRecorder) FetchJobByCompanyId(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobByCompanyId", reflect.TypeOf((*MockService)(nil).FetchJobByCompanyId), ctx, companyId)
}

// GetAllJobs mocks base method.
func (m *MockService) GetAllJobs(ctx context.Context) ([]models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJobs", ctx)
	ret0, _ := ret[0].([]models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJobs indicates an expected call of GetAllJobs.
func (mr *MockServiceMockRecorder) GetAllJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJobs", reflect.TypeOf((*MockService)(nil).GetAllJobs), ctx)
}

// GetJobById mocks base method.
func (m *MockService) GetJobById(ctx context.Context, jobId string) (models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobById", ctx, jobId)
	ret0, _ := ret[0].(models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobById indicates an expected call of GetJobById.
func (mr *MockServiceMockRecorder) GetJobById(ctx, jobId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobById", reflect.TypeOf((*MockService)(nil).GetJobById), ctx, jobId)
}

// JobByCompanyId mocks base method.
func (m *MockService) JobByCompanyId(jobs []models.JobReq, compId string) ([]models.JobRespo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobByCompanyId", jobs, compId)
	ret0, _ := ret[0].([]models.JobRespo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobByCompanyId indicates an expected call of JobByCompanyId.
func (mr *MockServiceMockRecorder) JobByCompanyId(jobs, compId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobByCompanyId", reflect.TypeOf((*MockService)(nil).JobByCompanyId), jobs, compId)
}

// VerifyEmailnDob mocks base method.
func (m *MockService) VerifyEmailnDob(ctx context.Context, data *models.ForgetPass) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailnDob", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmailnDob indicates an expected call of VerifyEmailnDob.
func (mr *MockServiceMockRecorder) VerifyEmailnDob(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailnDob", reflect.TypeOf((*MockService)(nil).VerifyEmailnDob), ctx, data)
}

// VerifyOtp mocks base method.
func (m *MockService) VerifyOtp(ctx context.Context, data *models.OTPcont) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOtp", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyOtp indicates an expected call of VerifyOtp.
func (mr *MockServiceMockRecorder) VerifyOtp(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOtp", reflect.TypeOf((*MockService)(nil).VerifyOtp), ctx, data)
}

// ViewCompanies mocks base method.
func (m *MockService) ViewCompanies(ctx context.Context) ([]models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewCompanies", ctx)
	ret0, _ := ret[0].([]models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewCompanies indicates an expected call of ViewCompanies.
func (mr *MockServiceMockRecorder) ViewCompanies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewCompanies", reflect.TypeOf((*MockService)(nil).ViewCompanies), ctx)
}
